#ifndef FCAUTOENCODER_GRAPHINFO_H
#define FCAUTOENCODER_GRAPHINFO_H
// Quantized scales can be used round_norm(val * QSCALE, QNORM) giving the real value in Q8
// Input_1
#define FCAutoEncoder_Input_1_OUT_SCALE	0.007810127921402454
#define FCAutoEncoder_Input_1_OUT_QSCALE	64
#define FCAutoEncoder_Input_1_OUT_QNORM	15
#define FCAutoEncoder_Input_1_OUT_ZERO_POINT	127
#define FCAutoEncoder_Input_1_Q	0
// S1__encoder_encoder_net_encoder_net_0_Gemm_weights
#define FCAutoEncoder_S1__encoder_encoder_net_encoder_net_0_Gemm_weights_OUT_SCALE	0.0003477353893686086
#define FCAutoEncoder_S1__encoder_encoder_net_encoder_net_0_Gemm_weights_OUT_QSCALE	91
#define FCAutoEncoder_S1__encoder_encoder_net_encoder_net_0_Gemm_weights_OUT_QNORM	18
#define FCAutoEncoder_S1__encoder_encoder_net_encoder_net_0_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S1__encoder_encoder_net_encoder_net_0_Gemm_weights_Q	0
// S2__encoder_encoder_net_encoder_net_0_Gemm_biases
#define FCAutoEncoder_S2__encoder_encoder_net_encoder_net_0_Gemm_biases_OUT_SCALE	2.7158578177477466e-06
#define FCAutoEncoder_S2__encoder_encoder_net_encoder_net_0_Gemm_biases_OUT_QSCALE	91
#define FCAutoEncoder_S2__encoder_encoder_net_encoder_net_0_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S2__encoder_encoder_net_encoder_net_0_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S2__encoder_encoder_net_encoder_net_0_Gemm_biases_Q	0
// S3__encoder_encoder_net_encoder_net_0_Gemm_fusion
#define FCAutoEncoder_S3__encoder_encoder_net_encoder_net_0_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S3__encoder_encoder_net_encoder_net_0_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S3__encoder_encoder_net_encoder_net_0_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S3__encoder_encoder_net_encoder_net_0_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S3__encoder_encoder_net_encoder_net_0_Gemm_fusion_Q	0
// S4__encoder_encoder_net_encoder_net_3_Gemm_weights
#define FCAutoEncoder_S4__encoder_encoder_net_encoder_net_3_Gemm_weights_OUT_SCALE	0.0004910433199256659
#define FCAutoEncoder_S4__encoder_encoder_net_encoder_net_3_Gemm_weights_OUT_QSCALE	64
#define FCAutoEncoder_S4__encoder_encoder_net_encoder_net_3_Gemm_weights_OUT_QNORM	17
#define FCAutoEncoder_S4__encoder_encoder_net_encoder_net_3_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S4__encoder_encoder_net_encoder_net_3_Gemm_weights_Q	0
// S5__encoder_encoder_net_encoder_net_3_Gemm_biases
#define FCAutoEncoder_S5__encoder_encoder_net_encoder_net_3_Gemm_biases_OUT_SCALE	1.925660078139866e-06
#define FCAutoEncoder_S5__encoder_encoder_net_encoder_net_3_Gemm_biases_OUT_QSCALE	65
#define FCAutoEncoder_S5__encoder_encoder_net_encoder_net_3_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S5__encoder_encoder_net_encoder_net_3_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S5__encoder_encoder_net_encoder_net_3_Gemm_biases_Q	0
// S6__encoder_encoder_net_encoder_net_3_Gemm_fusion
#define FCAutoEncoder_S6__encoder_encoder_net_encoder_net_3_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S6__encoder_encoder_net_encoder_net_3_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S6__encoder_encoder_net_encoder_net_3_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S6__encoder_encoder_net_encoder_net_3_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S6__encoder_encoder_net_encoder_net_3_Gemm_fusion_Q	0
// S7__encoder_encoder_net_encoder_net_6_Gemm_weights
#define FCAutoEncoder_S7__encoder_encoder_net_encoder_net_6_Gemm_weights_OUT_SCALE	0.0006928264629095793
#define FCAutoEncoder_S7__encoder_encoder_net_encoder_net_6_Gemm_weights_OUT_QSCALE	91
#define FCAutoEncoder_S7__encoder_encoder_net_encoder_net_6_Gemm_weights_OUT_QNORM	17
#define FCAutoEncoder_S7__encoder_encoder_net_encoder_net_6_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S7__encoder_encoder_net_encoder_net_6_Gemm_weights_Q	0
// S8__encoder_encoder_net_encoder_net_6_Gemm_biases
#define FCAutoEncoder_S8__encoder_encoder_net_encoder_net_6_Gemm_biases_OUT_SCALE	2.7169665212140363e-06
#define FCAutoEncoder_S8__encoder_encoder_net_encoder_net_6_Gemm_biases_OUT_QSCALE	91
#define FCAutoEncoder_S8__encoder_encoder_net_encoder_net_6_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S8__encoder_encoder_net_encoder_net_6_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S8__encoder_encoder_net_encoder_net_6_Gemm_biases_Q	0
// S9__encoder_encoder_net_encoder_net_6_Gemm_fusion
#define FCAutoEncoder_S9__encoder_encoder_net_encoder_net_6_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S9__encoder_encoder_net_encoder_net_6_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S9__encoder_encoder_net_encoder_net_6_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S9__encoder_encoder_net_encoder_net_6_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S9__encoder_encoder_net_encoder_net_6_Gemm_fusion_Q	0
// S10__encoder_encoder_net_encoder_net_9_Gemm_weights
#define FCAutoEncoder_S10__encoder_encoder_net_encoder_net_9_Gemm_weights_OUT_SCALE	0.0009678811766207218
#define FCAutoEncoder_S10__encoder_encoder_net_encoder_net_9_Gemm_weights_OUT_QSCALE	127
#define FCAutoEncoder_S10__encoder_encoder_net_encoder_net_9_Gemm_weights_OUT_QNORM	17
#define FCAutoEncoder_S10__encoder_encoder_net_encoder_net_9_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S10__encoder_encoder_net_encoder_net_9_Gemm_weights_Q	0
// S11__encoder_encoder_net_encoder_net_9_Gemm_biases
#define FCAutoEncoder_S11__encoder_encoder_net_encoder_net_9_Gemm_biases_OUT_SCALE	3.795612457336164e-06
#define FCAutoEncoder_S11__encoder_encoder_net_encoder_net_9_Gemm_biases_OUT_QSCALE	127
#define FCAutoEncoder_S11__encoder_encoder_net_encoder_net_9_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S11__encoder_encoder_net_encoder_net_9_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S11__encoder_encoder_net_encoder_net_9_Gemm_biases_Q	0
// S12__encoder_encoder_net_encoder_net_9_Gemm_fusion
#define FCAutoEncoder_S12__encoder_encoder_net_encoder_net_9_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S12__encoder_encoder_net_encoder_net_9_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S12__encoder_encoder_net_encoder_net_9_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S12__encoder_encoder_net_encoder_net_9_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S12__encoder_encoder_net_encoder_net_9_Gemm_fusion_Q	0
// S13__decoder_decoder_net_decoder_net_0_Gemm_weights
#define FCAutoEncoder_S13__decoder_decoder_net_decoder_net_0_Gemm_weights_OUT_SCALE	0.0013695902889594436
#define FCAutoEncoder_S13__decoder_decoder_net_decoder_net_0_Gemm_weights_OUT_QSCALE	90
#define FCAutoEncoder_S13__decoder_decoder_net_decoder_net_0_Gemm_weights_OUT_QNORM	16
#define FCAutoEncoder_S13__decoder_decoder_net_decoder_net_0_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S13__decoder_decoder_net_decoder_net_0_Gemm_weights_Q	0
// S14__decoder_decoder_net_decoder_net_0_Gemm_biases
#define FCAutoEncoder_S14__decoder_decoder_net_decoder_net_0_Gemm_biases_OUT_SCALE	5.370942309644876e-06
#define FCAutoEncoder_S14__decoder_decoder_net_decoder_net_0_Gemm_biases_OUT_QSCALE	90
#define FCAutoEncoder_S14__decoder_decoder_net_decoder_net_0_Gemm_biases_OUT_QNORM	24
#define FCAutoEncoder_S14__decoder_decoder_net_decoder_net_0_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S14__decoder_decoder_net_decoder_net_0_Gemm_biases_Q	0
// S15__decoder_decoder_net_decoder_net_0_Gemm_fusion
#define FCAutoEncoder_S15__decoder_decoder_net_decoder_net_0_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S15__decoder_decoder_net_decoder_net_0_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S15__decoder_decoder_net_decoder_net_0_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S15__decoder_decoder_net_decoder_net_0_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S15__decoder_decoder_net_decoder_net_0_Gemm_fusion_Q	0
// S16__decoder_decoder_net_decoder_net_3_Gemm_weights
#define FCAutoEncoder_S16__decoder_decoder_net_decoder_net_3_Gemm_weights_OUT_SCALE	0.0009794733487069607
#define FCAutoEncoder_S16__decoder_decoder_net_decoder_net_3_Gemm_weights_OUT_QSCALE	64
#define FCAutoEncoder_S16__decoder_decoder_net_decoder_net_3_Gemm_weights_OUT_QNORM	16
#define FCAutoEncoder_S16__decoder_decoder_net_decoder_net_3_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S16__decoder_decoder_net_decoder_net_3_Gemm_weights_Q	0
// S17__decoder_decoder_net_decoder_net_3_Gemm_biases
#define FCAutoEncoder_S17__decoder_decoder_net_decoder_net_3_Gemm_biases_OUT_SCALE	3.8410719557135714e-06
#define FCAutoEncoder_S17__decoder_decoder_net_decoder_net_3_Gemm_biases_OUT_QSCALE	64
#define FCAutoEncoder_S17__decoder_decoder_net_decoder_net_3_Gemm_biases_OUT_QNORM	24
#define FCAutoEncoder_S17__decoder_decoder_net_decoder_net_3_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S17__decoder_decoder_net_decoder_net_3_Gemm_biases_Q	0
// S18__decoder_decoder_net_decoder_net_3_Gemm_fusion
#define FCAutoEncoder_S18__decoder_decoder_net_decoder_net_3_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S18__decoder_decoder_net_decoder_net_3_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S18__decoder_decoder_net_decoder_net_3_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S18__decoder_decoder_net_decoder_net_3_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S18__decoder_decoder_net_decoder_net_3_Gemm_fusion_Q	0
// S19__decoder_decoder_net_decoder_net_6_Gemm_weights
#define FCAutoEncoder_S19__decoder_decoder_net_decoder_net_6_Gemm_weights_OUT_SCALE	0.000687626947183162
#define FCAutoEncoder_S19__decoder_decoder_net_decoder_net_6_Gemm_weights_OUT_QSCALE	90
#define FCAutoEncoder_S19__decoder_decoder_net_decoder_net_6_Gemm_weights_OUT_QNORM	17
#define FCAutoEncoder_S19__decoder_decoder_net_decoder_net_6_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S19__decoder_decoder_net_decoder_net_6_Gemm_weights_Q	0
// S20__decoder_decoder_net_decoder_net_6_Gemm_biases
#define FCAutoEncoder_S20__decoder_decoder_net_decoder_net_6_Gemm_biases_OUT_SCALE	2.69657626346338e-06
#define FCAutoEncoder_S20__decoder_decoder_net_decoder_net_6_Gemm_biases_OUT_QSCALE	90
#define FCAutoEncoder_S20__decoder_decoder_net_decoder_net_6_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S20__decoder_decoder_net_decoder_net_6_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S20__decoder_decoder_net_decoder_net_6_Gemm_biases_Q	0
// S21__decoder_decoder_net_decoder_net_6_Gemm_fusion
#define FCAutoEncoder_S21__decoder_decoder_net_decoder_net_6_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S21__decoder_decoder_net_decoder_net_6_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S21__decoder_decoder_net_decoder_net_6_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S21__decoder_decoder_net_decoder_net_6_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S21__decoder_decoder_net_decoder_net_6_Gemm_fusion_Q	0
// S22__decoder_decoder_net_decoder_net_9_Gemm_weights
#define FCAutoEncoder_S22__decoder_decoder_net_decoder_net_9_Gemm_weights_OUT_SCALE	0.0004904819070361555
#define FCAutoEncoder_S22__decoder_decoder_net_decoder_net_9_Gemm_weights_OUT_QSCALE	64
#define FCAutoEncoder_S22__decoder_decoder_net_decoder_net_9_Gemm_weights_OUT_QNORM	17
#define FCAutoEncoder_S22__decoder_decoder_net_decoder_net_9_Gemm_weights_OUT_ZERO_POINT	128
#define FCAutoEncoder_S22__decoder_decoder_net_decoder_net_9_Gemm_weights_Q	0
// S23__decoder_decoder_net_decoder_net_9_Gemm_biases
#define FCAutoEncoder_S23__decoder_decoder_net_decoder_net_9_Gemm_biases_OUT_SCALE	1.9234584589653153e-06
#define FCAutoEncoder_S23__decoder_decoder_net_decoder_net_9_Gemm_biases_OUT_QSCALE	65
#define FCAutoEncoder_S23__decoder_decoder_net_decoder_net_9_Gemm_biases_OUT_QNORM	25
#define FCAutoEncoder_S23__decoder_decoder_net_decoder_net_9_Gemm_biases_OUT_ZERO_POINT	0
#define FCAutoEncoder_S23__decoder_decoder_net_decoder_net_9_Gemm_biases_Q	0
// S24__decoder_decoder_net_decoder_net_9_Gemm_fusion
#define FCAutoEncoder_S24__decoder_decoder_net_decoder_net_9_Gemm_fusion_OUT_SCALE	0.00392156862745098
#define FCAutoEncoder_S24__decoder_decoder_net_decoder_net_9_Gemm_fusion_OUT_QSCALE	64
#define FCAutoEncoder_S24__decoder_decoder_net_decoder_net_9_Gemm_fusion_OUT_QNORM	14
#define FCAutoEncoder_S24__decoder_decoder_net_decoder_net_9_Gemm_fusion_OUT_ZERO_POINT	0
#define FCAutoEncoder_S24__decoder_decoder_net_decoder_net_9_Gemm_fusion_Q	0
// S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale
#define FCAutoEncoder_S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale_OUT_SCALE	0.00787397632448692
#define FCAutoEncoder_S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale_OUT_QSCALE	65
#define FCAutoEncoder_S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale_OUT_QNORM	13
#define FCAutoEncoder_S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale_OUT_ZERO_POINT	0
#define FCAutoEncoder_S25__decoder_decoder_net_decoder_net_11_BatchNormalization_scale_Q	0
// S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias
#define FCAutoEncoder_S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias_OUT_SCALE	0.007874015748031496
#define FCAutoEncoder_S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias_OUT_QSCALE	65
#define FCAutoEncoder_S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias_OUT_QNORM	13
#define FCAutoEncoder_S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias_OUT_ZERO_POINT	0
#define FCAutoEncoder_S26__decoder_decoder_net_decoder_net_11_BatchNormalization_bias_Q	0
// S27_expr_0
#define FCAutoEncoder_S27_expr_0_OUT_SCALE	0.005601411729347049
#define FCAutoEncoder_S27_expr_0_OUT_QSCALE	92
#define FCAutoEncoder_S27_expr_0_OUT_QNORM	14
#define FCAutoEncoder_S27_expr_0_OUT_ZERO_POINT	128
#define FCAutoEncoder_S27_expr_0_Q	0
// Output_1
#define FCAutoEncoder_Output_1_OUT_SCALE	0.005601411729347049
#define FCAutoEncoder_Output_1_OUT_QSCALE	92
#define FCAutoEncoder_Output_1_OUT_QNORM	14
#define FCAutoEncoder_Output_1_OUT_ZERO_POINT	128
#define FCAutoEncoder_Output_1_Q	0
#endif //FCAUTOENCODER_GRAPHINFO_H